- hosts: localhost
  gather_facts: no
  vars_files:
    - cred.yml
  tasks:
    - name:
      pip:
        name: boto3
        state: present

    - name: Create security group for AWS
      ec2_group:
        name: WebSG
        description: allowing http and ssh
        region: eu-north-1
        aws_accecess_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp 
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_engress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: lauch ec2 instance
      ec2:
        key_name: webkey
        inctance_type: t3.micro 
        image: ami-0e306788ff2473ccb
        wait: true
        group: WebSG
        count: 1
        vpc_subnet_id: vpc-3cf24d55
        assign_public_ip: yes
        region: eu-north-1
        state: present
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        instance_tags:
          Name: webserver
        register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: webserver
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        state: started
      loop: "{{ ec2.instances }}"

- hosts: webserver
  gather_facts: no
  tasks:
    - name: running role
      include_role:
        name: httpdserver
